name: Auto Sync on Changes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-tasks:
    runs-on: self-hosted

    steps:
      - name: Test runner funciona
        shell: cmd
        run: echo RUNNER OK - JOSEOVANDO funcionando correctamente

      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Info del commit
        shell: cmd
        run: |
          echo Repo: ${{ github.repository }}
          echo Rama: ${{ github.ref_name }}
          echo Actor: ${{ github.actor }}